# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jkauppi <jkauppi@student.hive.fi>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/07/09 11:14:18 by jkauppi           #+#    #+#              #
#    Updated: 2021/07/09 11:18:15 by jkauppi          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

.PHONY: all
all:
	@echo "Done!"

.PHONY: clean
clean:
	@echo "Done!"

.PHONY: fclean
fclean:
	@echo "Done!"
